site_name: Funding Program Manager
site_description: 'A guide for the Funding extension.'
site_author: SYSTOPIA
repo_url: https://github.com/systopia/funding
theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Naming conventions': naming-conventions.md
  - 'Administration':
    - 'Installation': administration/installation.md
    - 'Users and Permissions': administration/user-permissions.md
    - 'Necessary Adjustments': administration/necessary-adjustments.md
    - 'Administer Funding Programs': administration/funding-programs.md
    - 'Notification Emails': administration/notification-emails.md
  - 'Usage':
      - 'Introduction': usage/usage.md
      - 'Application States': usage/application-states.md
      - 'Usage for Applicants': usage/usage-applicants.md
      - 'Usage for Reviewers': usage/usage-reviewers.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
