site_name: Funding
repo_url: https://github.com/systopia/funding
site_description: 'A guide for the Funding extension.'
site_author: 'systopia'
theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Installation': installation.md
  - 'Configuration': configuration.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
